### ISSUE TITLE
Gpd renamed to groupoids

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/xmod#10]
This change has to be reflected in XMod's dependencies, otherwise it can not be loaded (and hence IdRel and XModAlg, both of which depend on XMod).

**Comment by cdwensley** [comment]
Indeed - will deal with this a.s.a.p.

**Comment by cdwensley** [comment]
xmod-2.61 just released (some methods temporarily removed; 3 test files renamed so as not to be tested).  Just noticed that XModAlg no longer compatible with XMod as Is2dDomain in XMod has been renamed Is2DimensionalDomain - will email Alper about this.

**Comment by alex-konovalov** [comment]
Thanks @cdwensley. I've also noticed that XModAlg URL http://fef.ogu.edu.tr/matbil/aodabas/xmodalg/PackageInfo.g is not available any more. @aodabas would you be able to make a new release to fix both issues, please? If you would like any help with migrating it GitHub, please let me know.

**Comment by cdwensley** [comment]
And thanks to you @alex-konovalov for clarifying the situation. 
I have had the following message from @aodabas:  "I am maintaining the XModAlg package. I am still working on a the another project in Ankara. I plan it moving to GitHub next month." 
Since he is otherwise occupied at present I have released XMod 2.62 this evening with 6 synonyms added to reintroduce function names changed in XMod but still used in XModAlg. 
These synonyms can be taken out again once a revised XModAlg is released. 
The XModAlg-1.12 test file now works for me, so I assume all is now OK?

**Comment by alex-konovalov** [comment]
@cdwensley thanks - yes, the new XMod 2.62 seems to resolve the problem. Then we can patiently wait until @aodabas will release new XModAlg.

**Comment by cdwensley** [comment]
@fingolfin - what's going on here?  Is there anything I should be doing? 
I've just noticed that there are still changes to make to XModAlg to agree with the name changes in XMod made last summer, and I plan to make a PR later this afternoon.

**Comment by cdwensley** [comment]
This was fixed back in August 2017.
